{% set name = "penaltymodel" %}
{% set version = "1.3.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/penaltymodel-{{ version }}.tar.gz
  sha256: 34af628916420218b16a8ceca608abbf8530b731fe05902392a3a3bceee395d0

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - pip
    - python {{ python_min }}
    - setuptools
  run:
    - dimod >=0.10.9
    - homebase >=1.0.1
    - networkx >=2.4.0
    - numpy >=1.20.0
    - python >={{ python_min }}
    - scipy >=1.6.0

test:
  imports:
    - penaltymodel
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/dwavesystems/penaltymodel
  summary: Package for creating penalty models.
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - BastianZim
